export const SolitairesData = {
  setting: {
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    fade: false,
    autoplaySpeed: 3000,
    arrows: false,
    arrowsImg: false,
    accessibility: false,
    centerMode: false,
    focusOnSelect: false,
    pauseOnHover: false,
    pauseOnDotsHover: false,
    pauseOnFocus: false,
    swipe: true,
  },
  setting1: {
    dots: false,
    infinite: true,
    autoplay: true,
    speed: 1000,
    fade: false,
    arrows: false,
    arrowsImg: true,
    dotsClass: "slickdev",
    accessibility: false,
    centerMode: false,
    focusOnSelect: false,
    pauseOnHover: false,
    pauseOnDotsHover: false,
    pauseOnFocus: false,
    swipe: true,
  },
  carouselData: [
    {
      img:
        "https://storage.googleapis.com/media.nacjewellers.com/resources/user_media/solitaires_listing_banner_1.png",
    },
  ],
  imageContent: "Solitaire jewellery that will take your breath away.",
  heading: "The Solitaire Collection",
  bodyContent:
    "For ages, Our country has had a rich pedigree in creating and consuming fine artistic jewellery. For thousands of years, it has charmed affluent locals, rulers, traders and foreigners alike. The yesteryear generations always had a rich fascination for authentic gold and gemstones of varying natures. The artistic craftsmen of yore, gave it various renditions, that still stand testimony to a bygone era.  ",
};
