export const SiteMapData =
    [
        {
            "categoryHeading": "Earrings",
            "categoryList":
                [
                    "Earrings",
                    "Hoops Earrings",
                    "Jhumkas Earrings",
                    "Sui Dhaga Earrings",
                    "Chandbali Earrings",
                    "Pearl Earrings",
                    "Platinum Earrings",
                    "Solitaire Earrings",
                    "Earcuff Earrings",
                    "Studs",
                    "Stud Earrings",
                    "Gold Stud Earrings",
                    "Diamond Stud Earrings",
                    "Stud Earrings For Men",
                    "Stud Earrings For Girls",
                    "Gold Earrings",
                    "Gold Earrings Designs For Daily Use",
                    "Gold Earrings For Girls",
                    "Gold Earrings For Men",
                    "Gold Stud Earrings",
                    "Gold Earrings Jhumka Design",
                    "Jhumka Earrings Gold",
                    "Sui Dhaga Gold Earrings",
                    "Gold Hoop Earrings",
                    "Chandbali Earrings Gold",
                    "Gold Pearl Earrings",
                    "Rose Gold Earrings",
                    "Gold Drop Earrings",
                    "White Gold Earrings",
                    "Yellow Gold Earrings",
                    "Diamond Earrings",
                    "Diamond Stud Earrings",
                    "Diamond Earrings For Men",
                    "Diamond Earrings For Women",
                    "Diamond Solitaire Earrings",
                    "Diamond Hoop Earrings",
                    "Diamond Drop Earrings",
                    "Diamond Chandbali Earrings",
                    "Diamond Sui Dhaga Earrings"
                ]

        },
        {
            "categoryHeading": "Rings",
            "categoryList":
                [

                    "Rings",
                    "Couple Rings",
                    "Mens Rings",
                    "Platinum Rings",
                    "Ring Finger",
                    "Couple Rings Gold",
                    "Solitaire Rings",
                    "Wedding Rings",
                    "Cocktail Rings",
                    "Ruby Ring",
                    "Pearl Ring",
                    "Navaratna Ring",
                    "Fancy Ring",
                    "Sapphire Rings",
                    "Adjustable Rings",
                    "Halo Ring",
                    "Midi Rings",
                    "Diamond Rings",
                    "Mens Diamond Rings",
                    "Diamond Rings For Women",
                    "Diamond Engagement Rings",
                    "Solitaire Diamond Ring",
                    "Diamond Band Ring",
                    "Diamond Cluster Ring",
                    "Gold Rings",
                    "Gold Ring For Men",
                    "Gold Ring For Women",
                    "Couple Rings Gold",
                    "Gold Engagement Rings",
                    "Simple Gold Ring",
                    "Rose Gold Rings",
                    "Gold Band Ring",
                    "Engagement Rings",
                    "Mens Engagement Rings",
                    "Platinum Engagement Rings",
                    "Solitaire Engagement Ring",
                    "Solitaire Engagement Ring",
                    "Solitaire Diamond Ring",
                    "Solitaire Ring For Men",
                    "Solitaire Ring For Women",
                    "Band Rings"
                ]

        },
        {
            "categoryHeading": "Mangalsutra",
            "categoryList":
                [
                    "Earrings",
                    "Hoops Earrings",
                    "Jhumkas Earrings",
                    "Sui Dhaga Earrings",
                    "Chandbali Earrings",
                    "Pearl Earrings",
                    "Platinum Earrings",
                    "Solitaire Earrings",
                    "Earcuff Earrings",
                    "Studs",
                    "Stud Earrings",
                    "Gold Stud Earrings",
                    "Diamond Stud Earrings",
                    "Stud Earrings For Men",
                    "Stud Earrings For Girls",
                    "Gold Earrings",
                    "Gold Earrings Designs For Daily Use",
                    "Gold Earrings For Girls",
                    "Gold Earrings For Men",
                    "Gold Stud Earrings",
                    "Gold Earrings Jhumka Design",
                    "Jhumka Earrings Gold",
                    "Sui Dhaga Gold Earrings",
                    "Gold Hoop Earrings",
                    "Chandbali Earrings Gold",
                    "Gold Pearl Earrings",
                    "Rose Gold Earrings",
                    "Gold Drop Earrings",
                    "White Gold Earrings",
                    "Yellow Gold Earrings",
                    "Diamond Earrings",
                    "Diamond Stud Earrings",
                    "Diamond Earrings For Men",
                    "Diamond Earrings For Women",
                    "Diamond Solitaire Earrings",
                    "Diamond Hoop Earrings",
                    "Diamond Drop Earrings",
                    "Diamond Chandbali Earrings",
                    "Diamond Sui Dhaga Earrings"
                ]

        },
        {
            "categoryHeading": "Other Jewellery",
            "categoryList":
                [
                    "Earrings",
                    "Hoops Earrings",
                    "Jhumkas Earrings",
                    "Sui Dhaga Earrings",
                    "Chandbali Earrings",
                    "Pearl Earrings",
                    "Platinum Earrings",
                    "Solitaire Earrings",
                    "Earcuff Earrings",
                    "Studs",
                    "Stud Earrings",
                    "Gold Stud Earrings",
                    "Diamond Stud Earrings",
                    "Stud Earrings For Men",
                    "Stud Earrings For Girls",
                    "Gold Earrings",
                    "Gold Earrings Designs For Daily Use",
                    "Gold Earrings For Girls",
                    "Gold Earrings For Men",
                    "Gold Stud Earrings",
                    "Gold Earrings Jhumka Design",
                    "Jhumka Earrings Gold",
                    "Sui Dhaga Gold Earrings",
                    "Gold Hoop Earrings",
                    "Chandbali Earrings Gold",
                    "Gold Pearl Earrings",
                    "Rose Gold Earrings",
                    "Gold Drop Earrings",
                    "White Gold Earrings",
                    "Yellow Gold Earrings",
                    "Diamond Earrings",
                    "Diamond Stud Earrings",
                    "Diamond Earrings For Men",
                    "Diamond Earrings For Women",
                    "Diamond Solitaire Earrings",
                    "Diamond Hoop Earrings",
                    "Diamond Drop Earrings",
                    "Diamond Chandbali Earrings",
                    "Diamond Sui Dhaga Earrings"
                ]

        },

    ]





