export const routes = {
  stylori: "/stylori",
  PricingPage: "/pricingPage",
  Cart: "/cart",
  Checkout: "/Checkout",
  Register: "/register",
  UserLogin: "/login",
  UserRegister: "/registers",
  HomePageStylori: "/",
  Account: `/account${"-" + window.location.pathname.split("-")[1]}`,
  Silver: "/stylorisilver",
  Faqs: "/faqs",
  Stories: "/stories",
  Collection: "/collections",
  ProductCare: "/productcare",
  Shipping: "/deliveryreturns",
  PrivacyPolicy: "/privacy",
  TermsConditions: "/termsconditions",
  AboutUs: "/aboutus",
  ForgotPassword: "/forgotpassword",
  ResetPassword: "/resetpassword",
  ChangePassword: "/changepassword",
  paymentsuccess: "/paymentsuccess",
  paymentfail: "/paymentfail",
  paymenthidden: "/paymenthidden",
  Education: "/education",
  ContactUs: "/contactus",
  Careers: "/careersPage",
  HomePage: "/homes",
  SavingsPage: "/savingscheme",
  ExperiencePage: "/experiences",
  AdvertisingPage: "/advertising",
  TempleWorkPage: "/temple-work",
  NewsRoomPage: "/newsroom",
  AboutUsPage: "/aboutus",
  // Terms: "/termsconditions",
  Return: "/return",
  Delivery: "/delivery",
  // Privacy: "/privacy",
  ContactPage: "/contactus",
  // EducationPage: "/education",
  SiteMap: "/sitemap",
  // Faq: "/faqs",
  StoreLocator: "/store",
  StoreDetail: "/loc/:id",
  CareersPage: "/careers",
  DigitalMarketing: "/careersDetail",
  Diamonds: "/solitaires-search",
  CollectionHomePage: "/collectionhome",
  rudramadeviBlog: "/rudramadeviBlog",
  Blog: "/blog",
  Solitaires: "/solitaires",
  CollectionPage: "/collectionPage",
  CollectionFullPage: "/collection",
  AkshyaTritiya: "/akshyaTritiya",
  BridalCollection: "/bridalCollection"
};

export default routes;
